# -*- coding: utf-8 -*-
"""SE_Block.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oJlg76htrMpft-GOx8o6v7klRWaUwmk6
"""

import torch
import torch.nn as nn
import torch.functional as F

# SENet은 SEBlock을 쌓아, 만든 모델입니다.

class SEBlock(nn.Module):
    def __init__(self, c, r = 16):
        super(SEBlock, self).__init__()
        self.squeeze = nn.AdaptiveAvgPool2d(1)
        self.excitation = nn.Sequential(
            nn.Linear(c, c // r, bias = False),
            nn.ReLU(inplace = True),
            nn.Linear(c // r, c, bias = False),
            nn.Sigmoid()
        )
    
    def forward(self, input_filter):
        batch, channel, _, _ = input_filter.size()
        se = self.squeeze(input_filter).view(batch, channel)
        se = self.excitation(se).view(batch, channel, 1, 1)

        return input_filter * se.expand_as(input_filter)

